
        <html>
        <head>
            <title>Issue #336: Fedora 35: Errors while installing with install script.</title>
        </head>
        <body>
            <h1>Fedora 35: Errors while installing with install script.</h1>
            <p><strong>Issue #336</strong></p>
            <div>
                <h2>Description</h2>
                <p>### Error output:
```
Setting up Python environment

./auto-cpufreq-installer: line 117: yum: command not found

Installing necessary Python packages

Requirement already satisfied: pip in /opt/auto-cpufreq/venv/lib/python3.10/site-packages (21.3.1)
Requirement already satisfied: setuptools in /opt/auto-cpufreq/venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (57.4.0)
Collecting psutil
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click in /opt/auto-cpufreq/venv/lib/python3.10/site-packages/click-8.0.3-py3.10.egg (from -r requirements.txt (line 3)) (8.0.3)
Requirement already satisfied: distro in /opt/auto-cpufreq/venv/lib/python3.10/site-packages/distro-1.6.0-py3.10.egg (from -r requirements.txt (line 4)) (1.6.0)
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Installing collected packages: psutil
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/auto-cpufreq/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4aqnagoq/psutil_d21ff1542b5c41b4b0a78b374d5e674d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4aqnagoq/psutil_d21ff1542b5c41b4b0a78b374d5e674d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3l71nx_9/install-record.txt --single-version-externally-managed --compile --install-headers /opt/auto-cpufreq/venv/include/site/python3.10/psutil
         cwd: /tmp/pip-install-4aqnagoq/psutil_d21ff1542b5c41b4b0a78b374d5e674d/
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.10
    creating build/lib.linux-x86_64-3.10/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.10/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.10/psutil
    creating build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.10/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.10/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.10
    creating build/temp.linux-x86_64-3.10/psutil
    gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -I/opt/auto-cpufreq/venv/include -I/usr/include/python3.10 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.10/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
        9 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/auto-cpufreq/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4aqnagoq/psutil_d21ff1542b5c41b4b0a78b374d5e674d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4aqnagoq/psutil_d21ff1542b5c41b4b0a78b374d5e674d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3l71nx_9/install-record.txt --single-version-externally-managed --compile --install-headers /opt/auto-cpufreq/venv/include/site/python3.10/psutil Check the logs for full command output.

-------------------------------------------------------------------------------

installing auto-cpufreq tool

running install
running bdist_egg
running egg_info
writing auto_cpufreq.egg-info/PKG-INFO
writing dependency_links to auto_cpufreq.egg-info/dependency_links.txt
writing requirements to auto_cpufreq.egg-info/requires.txt
writing top-level names to auto_cpufreq.egg-info/top_level.txt
reading manifest file 'auto_cpufreq.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'auto_cpufreq.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/auto_cpufreq
copying build/lib/auto_cpufreq/__init__.py -> build/bdist.linux-x86_64/egg/auto_cpufreq
copying build/lib/auto_cpufreq/core.py -> build/bdist.linux-x86_64/egg/auto_cpufreq
copying build/lib/auto_cpufreq/power_helper.py -> build/bdist.linux-x86_64/egg/auto_cpufreq
copying build/lib/auto_cpufreq/tlp_stat_parser.py -> build/bdist.linux-x86_64/egg/auto_cpufreq
byte-compiling build/bdist.linux-x86_64/egg/auto_cpufreq/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/auto_cpufreq/core.py to core.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/auto_cpufreq/power_helper.py to power_helper.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/auto_cpufreq/tlp_stat_parser.py to tlp_stat_parser.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.10/auto-cpufreq -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/auto-cpufreq to 755
copying auto_cpufreq.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying auto_cpufreq.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying auto_cpufreq.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying auto_cpufreq.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying auto_cpufreq.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying auto_cpufreq.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/auto_cpufreq-1.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing auto_cpufreq-1.0-py3.10.egg
Removing /opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.0-py3.10.egg
Copying auto_cpufreq-1.0-py3.10.egg to /opt/auto-cpufreq/venv/lib/python3.10/site-packages
auto-cpufreq 1.0 is already the active version in easy-install.pth
Installing auto-cpufreq script to /opt/auto-cpufreq/venv/bin

Installed /opt/auto-cpufreq/venv/lib/python3.10/site-packages/auto_cpufreq-1.0-py3.10.egg
Processing dependencies for auto-cpufreq==1.0
Searching for psutil
Reading https://pypi.org/simple/psutil/
Downloading https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz#sha256=0c9ccb99ab76025f2f0bbecf341d4656e9c1351db8cc8a03ccd62e318ab4b5c6
Best match: psutil 5.8.0
Processing psutil-5.8.0.tar.gz
Writing /tmp/easy_install-og8hkj56/psutil-5.8.0/setup.cfg
Running psutil-5.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-og8hkj56/psutil-5.8.0/egg-dist-tmp-7u0caqau
psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
    9 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1

```
---

### System information:
Cannot run install or debug commands due to this error message. I'm running:
* Fedora 35
* Kernel: 5.15.10-200.fc35.x86_64
* AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8) @ 2.300GHz 

```Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.0', 'auto-cpufreq')
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil' distribution was not found and is required by auto-cpufreq

```
---
Note: I also tried the snap method and encountered a similar issue. I can create a separate issue for that if needed.</p>
            </div>
            <div>
                <h2>Comments</h2>
        
                <div style="border: 1px solid #ccc; margin: 10px; padding: 10px;">
                    <p><strong>dolitehgreat97:</strong></p>
                    <p>I've seem to have found the error, or at least a solution to this problem: installing python3-devel has provided psutils and the install script works without errors. Which is odd seeing how I have the stand alone package installed.</p>
                </div>
            
                <div style="border: 1px solid #ccc; margin: 10px; padding: 10px;">
                    <p><strong>bobslept:</strong></p>
                    <p>We use `yum` in our installer script. This command is not found your system. See the error message:
`./auto-cpufreq-installer: line 117: yum: command not found`

This command is normally available on a fresh install of Fedora 35. And is just a symlink to dnf.

We do a `yum install python-devel` in the installer script which installs:

```
[beep@fedora ~]$ sudo yum install python-devel
Last metadata expiration check: 0:50:41 ago on Mon 27 Dec 2021 02:22:18 PM CET.
Package python3-devel-3.10.1-1.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```
So it exactly installs the package that fixed your problem.</p>
                </div>
            
                <div style="border: 1px solid #ccc; margin: 10px; padding: 10px;">
                    <p><strong>dolitehgreat97:</strong></p>
                    <p>Hmm, I don't have a fresh install, been upgrading since F33, so I'm unsure why I don't have that symlink. </p>
                </div>
            
            </div>
        </body>
        </html>
        